version: "3"

services:

  runtime-setup:
    image: swift-log:18.04-5.3
    build:
      args:
        base_image: "swiftlang/swift:nightly-master-bionic"

  test:
    image: swift-log:18.04-5.3
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-log:18.04-5.3
