version: "3"

services:

  runtime-setup:
    image: swift-log:20.04-5.7
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"

  test:
    image: swift-log:20.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-log:20.04-5.7
