name: PR

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift Logging API"

  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_6_0_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_6_1_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_6_2_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_6_0_enabled: true
      windows_6_1_enabled: true
      windows_6_2_enabled: true
      windows_nightly_next_enabled: true
      windows_nightly_main_enabled: true
      windows_6_0_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_6_1_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_6_2_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  benchmarks:
    name: Benchmarks (NoTraits)
    uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
    with:
      benchmark_package_path: "Benchmarks/NoTraits"
      macos_runner_pool: general
      macos_xcode_16_4_enabled: true
      macos_xcode_26_1_enabled: true

  benchmarks-MaxLogLevelWarningBenchmarks-trait:
    name: Benchmarks (MaxLogLevelWarning)
    uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
    with:
      benchmark_package_path: "Benchmarks/MaxLogLevelWarning"
      macos_runner_pool: general
      macos_xcode_26_1_enabled: true

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main

  static-linux:
    name: Static Linux Swift SDK
    # Workaround https://github.com/nektos/act/issues/1875
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@main

  macos-tests:
    name: macOS tests
    uses: apple/swift-nio/.github/workflows/macos_tests.yml@main
    with:
      runner_pool: general
      build_scheme: swift-log-Package
      swift_test_enabled: true

  android:
    name: Android Swift SDK
    # Workaround https://github.com/nektos/act/issues/1875
    uses: apple/swift-nio/.github/workflows/android_swift_sdk.yml@main

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@main
    with:
      windows_6_0_enabled: true
      windows_6_1_enabled: true
      windows_6_2_enabled: true
      windows_nightly_next_enabled: true
      windows_nightly_main_enabled: true

  wasm:
    name: Wasm Swift SDK
    uses: apple/swift-nio/.github/workflows/wasm_swift_sdk.yml@main
